config/routes.rb
Rails.application.routes.draw do

  get "/" => "sites#home"
  get "/contact" => "sites#contact"
  #get "/projects"=> "projects#index"
  #post "/projects"=> "projects#create"
  #get "/projects/new" => "projects#new"
  #get "/projects/:project_id/entries/new"=> "entries#new"
  #get "/projects/:project_id/entries"=> "entries#index"
  #get "/projects/:project_id"=> "projects#show"
  #post "/projects/:project_id/entries" => "entries#create", as: "project_entries"
  resources :projects, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
  	resources :entries, only: [:index, :new, :create]
  end

  resources :entries, only: [:edit, :update, :destroy]

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	validates :project, presence: true
	validates :hours, numericality: {only_integer: true, less_than: 24}
	validates :minutes, numericality: {only_integer: true, less_than: 60}
	validates :data, presence: true
	validates :hours, presence: true
	validates :minutes, presence: true

	belongs_to :project

	def total_minutes
		hours * 60 + minutes
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, uniqueness: true 
	validates :title, presence: true
	validates :title, length: {maximum: 30}
	validates :title, format: { with: /\A[A-Za-z0-9]/ }
	validates :priority, presence: true, inclusion: { in: [1, 2, 3, 4, 5]}
	
	has_many :entries, dependent: :destroy

	def self.iron_high_priority
		puts "in da class method"
		where("title like 'ironhack%' AND priority = 3")
	end

	def self.low_priority
		puts "Showing low priority projects"
		where("priority < 3")
	end

	def self.clean_low_priority
		puts "Let's make some cleaning..."
		projects = where(priority: 1)
		projects.destroy_all
	end

	def total_time
		entries.reduce(0) do |acc, entry|
			acc + entry.total_minutes
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@project = Project.find_by(id: params[:project_id])
		if @project.nil?
			render template: "shared/error"
		else
			@entries = @project.entries
		end
	end

	def new
		@project = Project.find_by(id: params[:project_id])
		@entry = Entry.new
	end

	def create
		project_id = params[:project_id]
		@project = Project.find_by(id: project_id)
		@entry = @project.entries.new(entry_params)

		#@entry = @project.entries.new({     	#todo esto se puede sustituir por la linea 
		#	hours: params[:entry][:hours],		#de arriba son equivalentes.
		#	minutes: params[:entry][:minutes],
		#	data: params[:entry][:data],
		#	comments: params[:entry][:comments]
		#	})

		if @entry.save
			redirect_to "/projects/#{@project.id}/entries"
		else
			render 'new'
		end
	end

	def edit
		@entry = Entry.find_by(id: params[:id])
	end

	def update
		@entry = Entry.find_by(id: params[:id])
		if @entry.update(entry_params)
			redirect_to project_entries_path(@entry.project.id)
		else
			render "edit"
		end
	end

	def destroy
		entry = Entry.find_by(id: params[:id])
		entry.destroy
		redirect_to project_entries_path(entry.project_id)
	end

	private
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :data, :comments)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
		render :index
	end

	def show
		@id = params[:id]
		
		@project = Project.find_by(id: @id)
		#render template "no_project" if @project.nil?
		
		render :show
	end

	def new
		@project = Project.new
	end

	def create

		@project = Project.new(entry_params)
		#@project = Project.new({
		#	title:params[:project][:title],
		#	description:params[:project][:description],
		#	priority:params[:project][:priority]
		#	})
		if @project.save
			redirect_to "/projects"
		else
			render :new
		end
	end

	def edit
		@project = Project.find_by(id: params[:id])
	end

	def update
		@project = Project.find_by(id: params[:id])
		if @project.update(entry_params)
			redirect_to projects_path
		else
			render :edit
		end
	end

	def destroy
		project = Project.find_by(id: params[:id])
		project.destroy
		redirect_to projects_path
	end

	private
	def entry_params
		params.require(:project).permit(:title, :description, :priority)
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

	def home
		render :home
	end

	def contact
		render :contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/entries/edit.html.erb
<h3>Edit entry</h3>
<hr>
<% if @entry.errors.any? %>
	<ul>
	<% @entry.errors.full_messages.each do |error_message| %>
		<li><%= error_message %></li>
		<% end %>
	</ul>
	<hr>
<% end %>
<%= form_for @entry do |f| %>
	<div>
		<%= f.number_field :hours, placeholder:"How many hours?" %>
	</div><br>
	<div>
		<%= f.number_field :minutes, placeholder:"How many minutes?" %>
	</div><br>
	<div>
		<%= f.date_field :data %>
	</div><br>
	<div>
		<%= f.text_area :comments, placeholder:"Insert a comment" %>
	</div><br>
	<%= f.submit "Change my time!" %>
	<button><%= link_to("Back to Entries", project_entries_path(@entry.project_id) ) %></button>
<%end%>
<hr>
<img src="http://www.funnfun.in/wp-content/uploads/2013/12/funny-cat-gif-animation.gif" alt="">

app/views/entries/index.html.erb
<h3>Title: <%= @project.title %></h3>
<button><a href=<%= project_path(@project.id) %>>Project page</a></button>
<button><a href=<%= projects_path %>>All the Projects</a></button>
<button><a href="<%=project_entries_path%>/new">Add entry</a></button>	
<p>
	You have worked <%= @project.total_time %> minutes on this project.
</p>

<% @entries.each do |entry| %>
			<li><%= "#{entry.hours} hours and #{entry.minutes} minutes on day #{entry.data.strftime(" %d/%m/%Y" )}" %>    <button><%= link_to("Edit Entry", edit_entry_path(entry.id)) %></button>
				<button><%= link_to("Delete", entry_path(entry), method: :delete, data: {confirm: "Are you sure?"}) %></button>
				<%if entry.comments != nil%>
					<%=" ==>  #{entry.comments}" unless entry.comments.nil? %>
				<%end%>
			</li>
		<%end%>
<br>
<hr>
<center><img src="http://data.whicdn.com/images/29996756/animated-cat-stickingout-tongue_large.gif" alt=""></center>

app/views/entries/new.html.erb
<h3>Create a new Entry</h3>
<hr>
<% if @entry.errors.any? %>
	<ul>
	<% @entry.errors.full_messages.each do |error_message| %>
		<li><%= error_message %></li>
		<% end %>
	</ul>
	<hr>
<% end %>
<%= form_for [@project, @entry] do |f| %>
	<div>
		<%= f.number_field :hours, placeholder:"How many hours?" %>
	</div><br>
	<div>
		<%= f.number_field :minutes, placeholder:"How many minutes?" %>
	</div><br>
	<div>
		<%= f.date_field :data %>
	</div><br>
	<div>
		<%= f.text_area :comments, placeholder:"Insert a comment" %>
	</div><br>
	<%= f.submit "Add my time!" %>
	<button><a href=<%=project_entries_path%>>Back to entries</a></button>
<%end%>
<hr>
<center><img src="https://media.giphy.com/media/rur945hryageI/giphy.gif" alt=""></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h3>Edit Project</h3>
<hr>
<% if @project.errors.any? %>
	<ul>
	<% @project.errors.full_messages.each do |error_message| %>
		<li><%= error_message %></li>
		<% end %>
	</ul>
	<hr>
<% end %>

<%= form_for @project do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title, placeholder:"write here a title" %>
	</div><br>
	<div>
		<%= f.label :priority %>
		<%= f.number_field :priority %>
	</div><br>
	<div>
		<%= f.label :description %>
		<%= f.text_area :description, placeholder:"description of the project" %>
	</div><br>
	<div>
		<%= f.submit "Edit the project" %>
		<button><a href="http://localhost:3000/projects">Back to project list</a></button>
	</div>
<%end%>
<hr>
<img src="https://s-media-cache-ak0.pinimg.com/originals/d8/6a/78/d86a7815dab0de4990f8f19c6cb79cc0.gif" alt="">

app/views/projects/index.html.erb
		<h1>All the projects: </h1>
		<br>
		<button><a href="http://localhost:3000/projects/new">Create a new Project</a></button>
		<hr>
		<% @projects.each do |project| %>
			<li>
				Title: <%= link_to(project.title, project_path(project.id)) %> 
				<%if project.description != nil%>
					<%=" ==>  #{project.description}" unless project.description.nil? %>
				<%end%>
			</li>
		<%end%>
		<hr>
		<img src="http://media0.giphy.com/media/pn8ZlwPvVClyM/giphy.gif" alt="">

app/views/projects/new.html.erb
<h1>create a new project</h1>
<hr>
<% if @project.errors.any? %>
	<ul>
	<% @project.errors.full_messages.each do |error_message| %>
		<li><%= error_message %></li>
		<% end %>
	</ul>
	<hr>
<% end %>

<%= form_for @project do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title, placeholder:"write here a title" %>
	</div><br>
	<div>
		<%= f.label :priority %>
		<%= f.number_field :priority %>
	</div><br>
	<div>
		<%= f.label :description %>
		<%= f.text_area :description, placeholder:"description of the project" %>
	</div><br>
	<div>
		<%= f.submit "Create a project" %>
		<button><a href="http://localhost:3000/projects">Back to project list</a></button>
	</div>
<%end%>
<hr>
<img src="http://www.gifbin.com/bin/500824yu29.gif" alt="">

app/views/projects/show.html.erb
<h1>Project show <%= @id %></h1>
<p>
	<%if Project.exists?(@id)%>
		<%= @project.title %> ==>
		<%= @project.description %>
	<%else%>
		<h3>There is no such project</h3>
	<%end%>
</p>
<p>
	<%= link_to("Back to projects", projects_path) %> / <%= link_to("show Project Entries", project_entries_path(@project.id)) %>  / <%= link_to("Edit Project", edit_project_path(@project.id)) %>  / <%= link_to("Delete Project", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}) %>
</p>
<img src="http://aftonnegrea.com/wp-content/uploads/2013/06/original.gif" alt="">

app/views/shared/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The project you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The project you were looking for doesn't exist.</h1>
      <p>You may have mistyped the id project or the project may not exist.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

app/views/sites/contact.html.erb
	<h3>This page has a contact email: </h3>
	<h1>awesome@contact.com</h1>

app/views/sites/home.html.erb
<center><h1>Time tracking!</h1></center>

<button><a href=<%= projects_path %>>projects</a></button>
<br>
<img src="http://media0.giphy.com/media/b3EqpdyuAfwmA/giphy.gif" alt="">